export const ALLOWED_PROMO_EVENTS = [
  'PromoEventPageView',
  'PromoEventAddPaymentInfo',
  'PromoEventAddToCart',
  'PromoEventCompleteRegistration',
  'PromoEventDonate',
  'PromoEventInitiateCheckout',
  'PromoEventLead',
  'PromoEventPurchase',
  'PromoEventSearch',
  'PromoEventStartTrial',
  'PromoEventSubmitApplication',
  'PromoEventSubscribe',
  'PromoEventViewContent',
];
